feat: add caching on docker repository

diff --git a/build-frontend/action.yml b/build-frontend/action.yml
--- a/build-frontend/action.yml
+++ b/build-frontend/action.yml
@@ -37,58 +37,57 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - name: Setup node
-      uses: actions/setup-node@v3
-      with:
-        node-version: 18.x
+    - name: Set up Docker Buildx
+      id: buildx
+      uses: docker/setup-buildx-action@v3
 
-    - name: Encode Basic Auth
-      id: base64-auth
+    - name: Login to Docker Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ${{ inputs.docker_registry_url }}
+        username: ${{ inputs.cloud_username }}
+        password: ${{ inputs.cloud_password }}
+
+    - name: Resolve values of the versions, docker ref & dockerfile path
+      id: resolve
       shell: bash
       run: |
-        echo "BASIC_AUTH_TOKEN=$(echo -n ${{ inputs.cloud_username }}:${{ inputs.cloud_password }} | base64 -w 0)" >> "$GITHUB_OUTPUT"
+        echo "version=${{ inputs.version || github.sha }}" >> $GITHUB_OUTPUT
+        echo "ref=${{ inputs.docker_registry_url }}/${{ inputs.project_name }}-storefrontcloud-io" >> $GITHUB_OUTPUT
+        if [[ $FRONTEND == "next" ]]; then
+          echo "path=.vuestorefrontcloud/docker/nextjs/Dockerfile-frontend" >> $GITHUB_OUTPUT
+        elif [[ $FRONTEND == "nextjs" ]]; then
+          echo "path=.vuestorefrontcloud/docker/nextjs/Dockerfile-frontend" >> $GITHUB_OUTPUT
+        elif [[ $FRONTEND == "nuxt" ]]; then
+          echo "path=.vuestorefrontcloud/docker/nuxtjs/Dockerfile-frontend" >> $GITHUB_OUTPUT
+        else
+          echo "Error: Unsupported FRONTEND value. Valid options are 'next' or 'nuxt'."
+          exit 1
+        fi
+      env:
+        FRONTEND: ${{ inputs.frontend }}
 
     - name: Check for existing image
       id: check-existing-image
       uses: javajawa/check-registry-for-image@v2
       with:
         registry: ${{ inputs.docker_registry_url }}
-        auth: "Basic ${{ steps.base64-auth.outputs.BASIC_AUTH_TOKEN }}"
         repository: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront
-        tag: ${{ inputs.version || github.sha }}
+        tag: ${{ steps.resolve.outputs.version }}
 
-    - name: Build and publish docker image (Next.js frontend)
-      if: ${{ inputs.frontend == 'next' || inputs.frontend == 'nextjs' }}
-      uses: elgohr/Publish-Docker-Github-Action@v5
+    - name: Build and publish docker image
+      uses: docker/build-push-action@v6
+      if: ${{ steps.check-existing-image.outputs.exists == 'false' }}
       with:
-        name: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront:${{ inputs.version || github.sha }}
-        registry: ${{ inputs.docker_registry_url }}
-        username: ${{ inputs.cloud_username }}
-        password: ${{ inputs.cloud_password }}
-        dockerfile: .vuestorefrontcloud/docker/nextjs/Dockerfile-frontend
-        buildoptions: --compress
-        buildargs: NPM_EMAIL,NPM_PASS,NPM_USER,NPM_REGISTRY,GIT_SHA
-      env:
-        NPM_EMAIL: ${{ inputs.npm_email }}
-        NPM_PASS: ${{ inputs.npm_pass }}
-        NPM_USER: ${{ inputs.npm_user }}
-        NPM_REGISTRY: ${{ inputs.npm_registry }}
-        GIT_SHA: ${{ inputs.version || github.sha }}
-
-    - name: Build and publish docker image (Nuxt frontend)
-      if: ${{ inputs.frontend == 'nuxt' }}
-      uses: elgohr/Publish-Docker-Github-Action@v5
-      with:
-        name: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront:${{ inputs.version || github.sha }}
-        registry: ${{ inputs.docker_registry_url }}
-        username: ${{ inputs.cloud_username }}
-        password: ${{ inputs.cloud_password }}
-        dockerfile: .vuestorefrontcloud/docker/nuxtjs/Dockerfile-frontend
-        buildoptions: --compress
-        buildargs: NPM_EMAIL,NPM_PASS,NPM_USER,NPM_REGISTRY,GIT_SHA
-      env:
-        NPM_EMAIL: ${{ inputs.npm_email }}
-        NPM_PASS: ${{ inputs.npm_pass }}
-        NPM_USER: ${{ inputs.npm_user }}
-        NPM_REGISTRY: ${{ inputs.npm_registry }}
-        GIT_SHA: ${{ inputs.version || github.sha }}
+        context: .
+        file: ${{ steps.resolve.outputs.path }}
+        push: true
+        tags: ${{ steps.resolve.outputs.ref }}/vue-storefront:${{ steps.resolve.outputs.version }}
+        cache-from: "type=registry,ref=${{ inputs.docker_registry_ref }}/vue-storefront:buildcache"
+        cache-to: "type=registry,ref=${{ inputs.docker_registry_ref }}/vue-storefront:buildcache,mode=max"
+        build-args: |
+          NPM_EMAIL=${{ inputs.npm_email }}
+          NPM_PASS=${{ inputs.npm_pass }}
+          NPM_USER=${{ inputs.npm_user }}
+          NPM_REGISTRY=${{ inputs.npm_registry }}
+          GIT_SHA=${{ steps.resolve.outputs.version }}
